name: MinrCheckpoint-5
main: org.minr.Zaraza107.MinrCheckpoint.Checkpoint
version: 5.alpha
author: Zaraza107, Nickman87, c_dric, Staartvin, evilmidget38
description: Level checkpoints for Minr.org
commands:
  checkpoint:
    description: MinrCheckpoint
    usage: /<command> [create <name> <X> <Y> <Z>]|[delete <checkpoint>]|[remove <player>]|[points <player>]|[ffa <player>]|[give <player> <value>]
